import { LocalizedStringKey } from "@/models/localization";

export default new Map<LocalizedStringKey, string>([
  [LocalizedStringKey.Button_Test, "Test"],
  
  [LocalizedStringKey.DailyGoal, "Daily Goal"],
  [LocalizedStringKey.LanguageName, "English"],
  [LocalizedStringKey.Term, "term"],
  
  [LocalizedStringKey.TermTag_Anatomy, "Anatomy"],
  [LocalizedStringKey.TermTag_Architecture, "Architecture"],
  [LocalizedStringKey.TermTag_Astronomy, "Astronomy"],
  [LocalizedStringKey.TermTag_Biochemistry, "Biochemistry"],
  [LocalizedStringKey.TermTag_Bird, "Bird"],
  [LocalizedStringKey.TermTag_Biology, "Biology"],
  [LocalizedStringKey.TermTag_Botany, "Botany"],
  [LocalizedStringKey.TermTag_Chemisty, "Chemistry"],
  [LocalizedStringKey.TermTag_Economy, "Economy"],
  [LocalizedStringKey.TermTag_Fish, "Fish"],
  [LocalizedStringKey.TermTag_Geography, "Geography"],
  [LocalizedStringKey.TermTag_Geology, "Geology"],
  [LocalizedStringKey.TermTag_Geometry, "Geometry"],
  [LocalizedStringKey.TermTag_Medicine, "Medicine"],
  [LocalizedStringKey.TermTag_Meteorology, "Meteorology"],
  [LocalizedStringKey.TermTag_Philosophy, "Philosophy"],
  [LocalizedStringKey.TermTag_Physics, "Physics"],
  [LocalizedStringKey.TermTag_Physiology, "Physiology"],
  [LocalizedStringKey.TermTag_Psychiatry, "Psychiatry"],
  [LocalizedStringKey.TermTag_Psychology, "Psychology"],
  [LocalizedStringKey.TermTag_Plant, "Plant"],
  [LocalizedStringKey.TermTag_Zoology, "Zoology"],
  
  [LocalizedStringKey.Text_DailyGoalReached, "You've reached your Daily Goal!"],
  [LocalizedStringKey.Text_SearchingFor, "Searching for"],
  [LocalizedStringKey.Text_SearchPlaceholder, "Search for term"],
  [LocalizedStringKey.Text_NumResultsFor, "results for"],
  [LocalizedStringKey.Text_NoResultsFor, "No results for"],
  
  [LocalizedStringKey.Title_DailyGoalReached, "Daily Goal reached!"],
  [LocalizedStringKey.Title_HistoryFromDate, "History from {date}"],
  [LocalizedStringKey.Title_HistoryOfToday, "Today's History"],
  [LocalizedStringKey.Title_HistoryOfYesterday, "Yesterday's History"],
  [LocalizedStringKey.Title_Language, "Language"],
  [LocalizedStringKey.Title_Settings, "Settings"],
  [LocalizedStringKey.Title_Search, "Search for Terms"],
])
